# Assignment 9

1. Implement naive bayes classification algorithm using Python /R to perform classification 
on a given dataset. 
2. Compute Confusion Matrix of findTP,FP,TN,FN,Accuracy, Error Rate, Precision,Recall on 
the given dataset

In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("Iris_6.csv")

In [8]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [9]:
X = df.iloc[:,1:5]
print(X) 

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]


In [10]:
Y = df.iloc[:,-1]

In [6]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=42)

In [12]:
from sklearn.naive_bayes import GaussianNB
sc = GaussianNB().fit(X_train,Y_train)

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_test_pred = sc.predict(X_test)
print(Y)
print(y_test_pred)


0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object
['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'

In [14]:
cm1 = confusion_matrix(Y_test,y_test_pred)
print(cm1)
acc = accuracy_score(Y_test,y_test_pred)
print(acc)

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
0.96


In [15]:
#for setosa class
tp = cm1[0][0]
fn = cm1[0][1] + cm1[0][2]
fp = cm1[1][0] + cm1[2][0]
tn = cm1[1][1] + cm1[1][2] + cm1[2][1] + cm1[2][2]
total = tp+fp+tn+fn
print('Error rate:')
error= (fp+fn)/total
print(error)

Error rate:
0.0


In [16]:
#for Versicolor
tp = cm1[1][1]
fn = cm1[1][0]+cm1[1][2]
fp = cm1[0][1] + cm1[2][1]
tn = cm1[0][0] + cm1[0][2] + cm1[2][0] + cm1[2][2]
total = tp+fn+fp+tn
print('Error rate:')
error = (fp+fn)/total
print(error)

Error rate:
0.04


In [17]:
#for Virginica
tp = cm1[2][2]
fn = cm1[2][0] + cm1[2][1]
fp = cm1[0][2] + cm1[1][2]
tn = cm1[0][0] + cm1[0][1] + cm1[1][0] +cm1[1][1]
total = tp+fn+fp+tn
print('Error rate:')
error = (fp+fn)/total
print(error)

Error rate:
0.04


In [18]:
from sklearn.metrics import classification_report
print('                     Classification Report:')
print(' ')
print(classification_report(Y_test,y_test_pred))

                     Classification Report:
 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.93      0.93      0.93        15
 Iris-virginica       0.94      0.94      0.94        16

       accuracy                           0.96        50
      macro avg       0.96      0.96      0.96        50
   weighted avg       0.96      0.96      0.96        50

